### ISSUE TITLE
Channels with the same name handling

### ISSUE THREAD

**Issue by DenisSch** [DenisSch/Quantification#12]
@JoshuaHess12 What happens exactly if two marker names are identical? Can we add a unique number (position in marker table) so they don't get removed.

**Comment by JoshuaHess12** [comment]
Right now the marker names are getting cut off because they are stored in a
python dictionary with the same keys if they have the same name. Would you
want to add a suffix/counter to the end of names or have the original names
instead with only different positions? For example, have a suffix for each
(Hoechst_1, Hoechst_2)? Or keep the original name with a different column
in the resulting csv file?

**Comment by DenisSch** [comment]
I would prefer HOECHST_1 etc

**Comment by DenisSch** [comment]
Tested - works great! Thank you!
