### ISSUE TITLE
Enable "minimal" and "full" CSV loading

### ISSUE THREAD

**Issue by DenisSch** [DenisSch/Quantification#14]
@JoshuaHess12 Do you have an idea how to enable the minimal loading (where only a list of names is provided) if the full CSV (which I have implemented now in 1.2.0) fails.
That would enable backwards compatibility.

**Comment by JoshuaHess12** [comment]
@DenisSch we could possibly include a small check after loading the csv file to see if the columns headers match the CyCIF pipeline csv structure (which you have implemented just now), and if they don't then we could assume that the csv structure is a single-column csv with the only column being the one used to indicate marker names (titled "marker_name"). How does this sound? For example, check if the pandas data frame contains the column titled "marker_name" and "cycle_number",  and if it does then great it will be a CyCIF structured channel list -- otherwise we can assume the only important column is the "marker_name".

**Comment by DenisSch** [comment]
That’s sounds exactly what we need.

**Comment by DenisSch** [comment]
Adressed by 1.2.1
