### ISSUE TITLE
If marker_name not available it throws an error

### ISSUE THREAD

**Issue by DenisSch** [DenisSch/Quantification#16]
@JoshuaHess12 
https://github.com/labsyspharm/quantification/blob/9e9475f98e656ea426b11967a6496bf77a641098/SingleCellDataExtraction.py#L171

**Comment by DenisSch** [comment]
@JoshuaHess12 I tried to make some changes, but it still does not work. Sniffer function fails...

**Comment by JoshuaHess12** [comment]
If the problem is with single column CSVs without a header, we could
instead check if the number of columns in the loaded CSV has more than one
column. If it does, then we can use the “marker_name” channel. If not, we
can introduce the “marker” column like the old channel name reader. This is
a bit hacky and may require two different instances of reading the csv file
but it would work I believe. What are your thoughts?

**Comment by JoshuaHess12** [comment]
Created a pull request for this.

**Comment by DenisSch** [comment]
@JoshuaHess12 It works :) I tested on both cases local and o2.
